### ISSUE TITLE
Sprint Signup : Already registered users are allowed to Signup multiple times

### ISSUE THREAD

**Issue by wolfie-90** [sprintrest/support#11]
User : dedeepyadodla@gmail.com

First Signup : Created user with workspace Sprint. User created successfully.
Now logged on to : https://sprint.rest
Again signed up with same user details 
Name : Dedeepya Dodla
Email : dedeepyadodla@gmail.com
Workspace : Sprint (2nd Time), SprintSignUp(3rd Time)

Issue1 :  Registered users, should get an error saying they are already registered.

All the time I see that workspace is Sprint which is created first time, so we are not overriding workspace created first.
<img width="1619" alt="Screenshot 2024-01-07 at 12 40 32 AM" src="https://github.com/sprintrest/support/assets/59585212/0250b69a-fe80-4d9a-97fe-fd2bd5ea7634">

**Comment by cloudsolace** [comment]
Issue is fixed

**Comment by ilkan** [comment]
Passed

**Comment by cloudsolace** [comment]
You can close the issue if its passed

**Comment by ilkan** [comment]
Could not see the Close Issue buton. @wolfie-90 might see it.
