### ISSUE TITLE
TestSuite : Issue with Duplicate feature

### ISSUE THREAD

**Issue by wolfie-90** [sprintrest/support#12]
Navigate to Test Suites.
Click on duplicate at folder level -> New folder is not created.
Click on duplicate at Test Case level -> New Test case created, but then in the side nav is not expanded view.

PFA Screen recording
[Screen Recording 2024-01-07 at 12.32.19 PM.mov.zip](https://github.com/sprintrest/support/files/13854554/Screen.Recording.2024-01-07.at.12.32.19.PM.mov.zip)

**Comment by cloudsolace** [comment]
The design is changed hence this issue has become stale.
<img width="1398" alt="image" src="https://github.com/sprintrest/support/assets/87838981/89c37fb6-c80a-49fe-a96c-2131b5544165">
