### ISSUE TITLE
🐛 [BUG] - White Screen on Sprint_0.9.19_x64_win.exe

### ISSUE THREAD

**Issue by ilkan** [sprintrest/support#52]
### Description

I've downloaded [Sprint_0.9.19_x64_win.exe](https://github.com/sprintrest/support/releases/download/v0.9.19/Sprint_0.9.19_x64_win.exe) 

Open app see white screen

### Reproduction URL

https://github.com/sprintrest/support/releases/download/v0.9.19/

### Reproduction steps

```bash
1. Click on 'https://github.com/sprintrest/support/releases/download/v0.9.19/Sprint_0.9.19_x64_win.exe'
2. Install
3. Open App
4. See white screen

Expected Sign In/Sign Up
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows

**Comment by cloudsolace** [comment]
Please try with v20

**Comment by ilkan** [comment]
![image](https://github.com/sprintrest/support/assets/5011210/245cb896-5ffd-4948-ada3-948fec8a17c8)
Same for "Windows 11 Home Single Language" - Windows Feature Experience Pack 1000.22684.1000.0 - OS Build 22621.3155

**Comment by ilkan** [comment]
Still same in 21
