### ISSUE TITLE
🐛 [BUG] - Windows Do not want to Download the App 

### ISSUE THREAD

**Issue by ilkan** [sprintrest/support#53]
### Description

[Sprint_0.9.19_x64_win.exe](https://github.com/sprintrest/support/releases/download/v0.9.19/Sprint_0.9.19_x64_win.exe)

Windows found this file suspicious. You need to add certification.

### Reproduction URL

https://github.com/sprintrest/support/releases/tag/v0.9.19

### Reproduction steps

```bash
1. Click on 'https://github.com/sprintrest/support/releases/download/v0.9.19/Sprint_0.9.19_x64_win.exe'
2. See "Windows do not want to download"

Expected not to see this pop-up
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Windows

**Comment by darkangel081195** [comment]
@ilkan windows app is already signed with EV certificate
