### ISSUE TITLE
🐛 [BUG] - The Login Screen Does Not Appear After Signing Out

### ISSUE THREAD

**Issue by ilkan** [sprintrest/support#57]
### Description

When I sign out, the name of the session owner does not appear, but the same screen remains. When I click on tabs such as environment and runs on the screen, an x ​​sign appears. Instead, I expected for it to be directed to the login screen when I sign out.
<img width="1440" alt="Sign out" src="https://github.com/sprintrest/support/assets/5011210/54ed336b-9262-423f-be12-0327cb32129e">

### Reproduction URL

desktop app

### Reproduction steps

```bash
1. Go to 'Desktop App'
2. Click on ''Sign in to Sprint'
3. Click on ''Sign out'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Browsers

Chrome

### OS

Mac

**Comment by cloudsolace** [comment]
This is fixed now
